name: Test AWS Role Setup

on:
  push:
    branches: [main, test]

jobs:
  test-aws-setup:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # Required for OIDC
      contents: read    # Required for actions/checkout

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::763378478523:role/shefffran-test-oidc-deploy-yml-connection-test
          aws-region: us-east-2

      - name: Test OIDC
        run: aws sts get-caller-identity


