name: CI

on:
  push:
    branches: [main, test]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Deploy to ${{ github.ref_name }}
        run: echo "Will deploy to ${{ github.ref_name }}"


      - name: Determine AWS Role
        id: role
        run: |
          case "${GITHUB_REF_NAME}" in
            main|qa)
              echo "role_arn=arn:aws:iam::763378478523:role/dcoc-oidc-github-test-connection" >> $GITHUB_OUTPUT
              ;;
            test|production)
              echo "role_arn=arn:aws:iam::123456789012:role/dcoc-oidc-github-prod-connection" >> $GITHUB_OUTPUT
              ;;
            *)
              echo "No role mapping for this branch"
              exit 1
              ;;
          esac

      - name: Configure AWS via OIDC
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ steps.role.outputs.role_arn }}
          aws-region: us-west-2

      - run: npm run build:${{ github.ref_name }}

      - name: Deploy
        run: |
          aws s3 sync --delete ./dist s3://${{ secrets.BUCKET }}
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_ID }} --paths "/*"
          
